project:
  type: website
  output-dir: docs

website:
  title: "BenKorea"
  
  navbar:
    left:
      - text: "Blog"
        href: index.qmd
      - text: "IT"      
        href: posts/IT/introduction.qmd
      - text: "Oncology"
        href: posts/Oncology/index.qmd
      - text: "Anatomy"
        href: posts/Anatomy/index.qmd         
      - text: "About"      
        href: posts/about.qmd     
    
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
    search: true
  
  sidebar:
    - title: "IT"
      collapse-level: 2    
      contents:
        - posts/IT/introduction.qmd
        - section: "Rasberry Pi"
          contents:
            - posts/IT/Rasberry_Pi/setup.qmd
        - section: "무소음 PC"
          contents:
            - posts/IT/silent_pc/silent_pc.qmd            

    - title: "Oncology"
      collapse-level: 2
      contents:
        - posts/Oncology/index.qmd
        - section: "NSCLC"
          contents:
          - posts/Oncology/NSCLC/staging.qmd
        - section: "SCLC"
          contents:
          - posts/Oncology/SCLC/staging.qmd     
        - section: "Prostate Cancer"
          contents:
          - posts/Oncology/Prostate_Cancer/staging.qmd               
        - section: "Anal Carcinoma"
          contents:
          - posts/Oncology/Anal_Carcinoma/staging.qmd          
    - title: "Anatomy"
      collapse-level: 2
      contents:
        - posts/Anatomy/index.qmd
        - section: "Pelvis"
          contents:
          - posts/Anatomy/pelvis/pelvis.qmd          
        
        
        
format:
  html:
    theme: cosmo
    css: styles.css
    comments:
      utterances:
        repo: BenKorea/website

editor: visual