project:
  type: website
  output-dir: ./docs

website:
  title: "BenKorea Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: quarto.qmd
        text: quarto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

