project:
  type: website
  output-dir: docs

website:
  title: "BenKorea"
  
  navbar:
    left:
      - text: Blog
        href: index.qmd
      - text: "PETCT Interpretation"
        href: posts/petct/index.qmd
      - text: "LN station"
        href: posts/station/index.qmd        
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
    search: true
    
  sidebar:
    - title: "PETCT Interpretation"
      collapse-level: 1
      contents:
        - posts/petct/index.qmd
        - section: "Anal Carcinoma"
          contents:
          - posts/petct/analcarcinoma/staging.qmd
    - title: "LN station"
      collapse-level: 1
      contents:
        - posts/station/index.qmd
        - section: "Pelvis"
          contents:
          - posts/station/pelvis/pelvis.qmd          
        
        
        
format:
  html:
    theme: cosmo
    css: styles.css
    comments:
      utterances:
        repo: BenKorea/website

editor: visual